### ISSUE TITLE
Change Highlight Style

### ISSUE THREAD

**Issue by rickylqhan** [rickylqhan/0b01#6]
Multiline highlight style should be:

1. opaque
2. continuous across lines - as in no separation
3. rounded squircle

As a style guide, this is YC's ```.btn`` class:

```css
.btn {
    font-family: "Avenir Heavy", Helvetica, Arial, sans-serif;
    color: #FFF;
    font-size: 1.8rem;
    line-height: 1.6;
    display: inline-block;
    text-shadow: 0 1px 1px rgba(0,0,0,0.2);
    padding: 5px 10px 5px 10px;
    border-radius: 7px;
    border: none;
    white-space: nowrap;
}
```
